version: '3.8'
services:
  api:
    build: 
        context: ./api
        dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3005:3005"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: HOSP
      POSTGRES_PORT: 5432
      POSTGRES_HOST: 192.168.146.137
    volumes:
      # Maps our current project directory `.` to
      # our working directory in the container
      - ./api:/app/api/
      # node_modules workaround for volumes
      # https://stackoverflow.com/a/32785014
      - /app/api/node_modules

 
  db:
    build: 
        context: ./postgres
        dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: HOSP
    volumes:
      # When the PostgreSQL container is started it will run any scripts
      # provided in the `docker-entrypoint-initdb.d` directory, this connects
      # our seed file to that directory so that it gets run
      - ./postgres-data:/var/lib/postgresql/data
